# Generated by Django 5.0.4 on 2024-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='displayed_name',
        ),
    ]
