# Generated by Django 4.2.11 on 2024-04-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(-1, 'Not Helpful'), (0, 'Neutral'), (1, 'Helpful')]),
        ),
    ]
