# Generated by Django 5.0.4 on 2024-04-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_username_profile_displayed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
